--- 
document: 
  description: |
    Questo documento descrive il processo di costruzione del modello di siti web
    per i Comuni italiani. Definisce i criteri e le modalità di realizzazione e
    contiene tutti i riferimenti ai documenti più importanti relativi al
    progetto.    
  name: "Design dei siti web dei Comuni italiani"
  tags: 
    - siti web
    - design
    - comuni 
